#!/usr/sbin/bash

function breaker() {
  [[ $# == 2 ]] && code=$2 || code=1
  echo -e "\033[38;5;160m$1\033[0m"
  return "$2" &>/dev/null \; exit "$2"
}

notify=`which dunstify`
notify=${notify:=`which notify-send`}
dependencies=(acpi espeak-ng $notify)

for d in ${dependencies[@]}
do
  if [[ ! `which $d 2>/dev/null` ]]
  then
    $notify 'Error' "$d is missing"
    breaker "Missing: $d" 1
  fi
done

while true
do
  iter=$(acpi|awk -F ',' '{print $2}'|awk -F '%' '{print $1}')
  SLEEP=
  if [ $iter -lt 15 ] 
  then
      SLEEP=180
      $notify 'Battery: ' "$(acpi)\nSleep: $SLEEP"
      espeak-ng "Battery ${iter}%" 
  fi
  sleep ${SLEEP:-300}
  unset iter
done
